# Generated by Django 6.0.4 on 2026-05-01 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_normalized', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('company_normalized', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('remote', models.BooleanField()),
                ('url', models.URLField(max_length=255)),
                ('description_raw', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.country')),
                ('tags', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.tag')),
            ],
        ),
    ]
